def site_header(file, navigation, brand):
    links = ''.join(f'<a href="{url}"'+(' aria-current="page"' if file == url else '')+f'><span class="menu-number">0{i+1}</span><span>{label}</span><span class="menu-arrow" aria-hidden="true">↗</span></a>' for i, (url, label) in enumerate(navigation))
    desktop = ''.join(f'<a href="{url}"'+(' aria-current="page"' if file == url else '')+f'>{label}</a>' for url, label in navigation[:3])
    return f'''<header class="header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="Metehan Çakal — ana sayfa">{brand}</a><nav class="desktop-nav" aria-label="Ana menü">{desktop}</nav><div class="header-actions"><a class="header-appointment" href="iletisim.html">Görüşme planlayın <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Menüyü aç"><span class="menu-label">Menü</span><span class="hamburger" aria-hidden="true"><span></span><span></span></span></button></div></div></header><dialog class="menu-panel" id="navigation" aria-labelledby="menu-heading"><div class="menu-panel-top"><span id="menu-heading">KEŞFEDİN</span><button class="menu-close" aria-label="Menüyü kapat"><span>Kapat</span><span aria-hidden="true">×</span></button></div><nav class="nav" aria-label="Tüm sayfalar">{links}<a class="menu-contact-link" href="iletisim.html"><span class="menu-number">05</span><span>İletişim</span><span class="menu-arrow" aria-hidden="true">↗</span></a></nav><div class="menu-panel-bottom"><span>Uzman Psikolojik Danışman<br><strong>Metehan Çakal</strong></span><a href="tel:+905432776463">0 543 277 64 63 <span aria-hidden="true">↗</span></a></div></dialog>'''


def contact_section(whatsapp):
    return f'''<section class="contact-band" aria-labelledby="contact-title"><div class="wrap contact-inner"><div class="contact-statement"><div class="eyebrow"><span class="section-index">06 /</span> İLETİŞİM & RANDEVU</div><h2 id="contact-title">Bir konuşma.<br><em>Yeni bir bakış.</em></h2><p>Görüşme seçeneklerini ve çalışma biçimini konuşalım. İlk temas için kısa bir mesaj yeterli.</p><div class="contact-person"><img src="assets/metehan-portre.jpg" alt="" loading="lazy" width="64" height="64"><span><strong>Metehan Çakal</strong><small>Uzman Psikolojik Danışman</small></span></div><svg class="contact-thread" viewBox="0 0 420 140" fill="none" aria-hidden="true"><path d="M2 110c85 0 111-100 190-100 78 0 63 116-3 116S133 35 219 35c68 0 64 64 199 64"/><path d="M2 121c92 0 114-98 190-98 62 0 54 93-3 93s-40-70 30-70c68 0 60 62 199 62"/></svg></div><div class="contact-desk"><div class="contact-desk-head"><span>İLK TEMAS</span><span>Online danışmanlık <span class="desk-dot" aria-hidden="true"></span></span></div><a class="contact-card primary" href="{whatsapp}"><span class="contact-method">WHATSAPP</span><strong>Görüşme planlayın</strong><span class="contact-action-icon" aria-hidden="true">↗</span></a><a class="contact-card" href="tel:+905432776463"><span class="contact-method">TELEFON</span><strong>0 543 277 64 63</strong><span class="contact-action-icon" aria-hidden="true">↗</span></a><a class="contact-email" href="mailto:metehncakal@gmail.com">metehncakal@gmail.com <span aria-hidden="true">↗</span></a><p class="contact-desk-note">Güncel ücret, uygun zamanlar ve görüşme koşulları ilk iletişimde netleştirilir.</p></div></div></section>'''


def site_footer(navigation, brand):
    links = ''.join(f'<a href="{url}">{label}</a>' for url, label in navigation)
    return f'''<footer class="footer footer-refined"><div class="wrap"><div class="footer-layout"><div class="footer-identity"><a class="brand footer-brand" href="index.html" aria-label="Metehan Çakal — ana sayfa">{brand}</a><p>Psikolojik danışmanlıkta, sizi ve yaşamınızı birlikte anlamaya odaklanan bir yaklaşım.</p><span class="footer-location">Düzce <span aria-hidden="true">/</span> Online görüşme</span></div><div class="footer-pages"><h3>Keşfedin</h3><nav class="footer-navigation" aria-label="Alt menü">{links}<a href="https://www.metehancakal.com/blog">Yazılar & kaynaklar</a></nav></div><div class="footer-reach"><h3>İletişim</h3><a class="footer-phone" href="tel:+905432776463">0 543 277 64 63 <span aria-hidden="true">↗</span></a><a class="footer-mail" href="mailto:metehncakal@gmail.com">metehncakal@gmail.com</a><address>Kültür Mahallesi, Mehmet Akif Caddesi<br>Güneş İş Merkezi · No: 14, Kat: 3, Ofis: 12<br>Merkez / Düzce</address><a class="footer-directions" href="iletisim.html">Randevu ve ulaşım <span aria-hidden="true">↗</span></a></div></div><div class="footer-legal"><span>© 2026 Metehan Çakal</span><div><a href="gizlilik.html">Gizlilik bilgisi</a><a class="footer-return" href="#top">Başa dön <span aria-hidden="true">↑</span></a></div></div><p class="footer-disclaimer">Bu sitedeki bilgiler kişisel değerlendirme ve tedavinin yerine geçmez.</p></div></footer>'''


def line_art(kind):
    shapes = [
        '<path d="M22 66c20-58 58-58 72-17s-48 66-52 21 60-52 94-11"/><path d="M26 80c22-60 58-61 73-20s-44 69-48 23 61-52 92-8"/>',
        '<ellipse cx="80" cy="59" rx="58" ry="18" transform="rotate(-35 80 59)"/><ellipse cx="80" cy="59" rx="58" ry="18" transform="rotate(35 80 59)"/><ellipse cx="80" cy="59" rx="58" ry="18" transform="rotate(90 80 59)"/>',
        '<path d="M18 95h24V73h25V51h25V29h25V8h27"/><path d="M18 107h37V85h25V63h25V41h25V20h15"/>',
        '<path d="M24 106V61a56 56 0 0 1 112 0v45M38 106V61a42 42 0 0 1 84 0v45M52 106V61a28 28 0 0 1 56 0v45M66 106V61a14 14 0 0 1 28 0v45"/>',
    ]
    return f'<svg class="area-art" viewBox="0 0 160 120" fill="none" stroke="currentColor" stroke-width="1.2" aria-hidden="true">{shapes[kind]}</svg>'


def homepage(areas, act, faq_html, contact, whatsapp):
    area_cards = ''.join(
        f'''<a class="area" href="calisma-alanlari.html#{id}"><span class="num">0{i + 1}</span><div class="area-title"><h3>{title}</h3><span class="area-tags">{tags}</span></div><p>{desc}</p><div class="area-illustration">{line_art(i)}<span class="area-arrow" aria-hidden="true">↗</span></div></a>'''
        for i, (id, title, desc, tags) in enumerate(areas)
    )
    nodes = ''.join(
        f'<button class="orbit-node node-{i}" id="act-tab-{i}" role="tab" aria-selected="{str(i == 0).lower()}" aria-controls="act-panel" tabindex="{0 if i == 0 else -1}" data-act="{i}"><span class="node-dot" aria-hidden="true"></span><span>{title}</span></button>'
        for i, (title, _) in enumerate(act)
    )
    return f'''
<section class="hero" aria-labelledby="hero-title"><div class="hero-stage">
  <div class="hero-stage-meta"><span>METEHAN ÇAKAL · UZMAN PSİKOLOJİK DANIŞMAN</span><span>ACT / ONLINE GÖRÜŞME</span></div>
  <div class="hero-inner"><div class="hero-copy"><div class="hero-kicker"><span aria-hidden="true">—</span> Anlamakla başlayan bir süreç.</div><h1 id="hero-title">Kendinize<br>başka bir<br><em>yerden bakın.</em></h1><div class="hero-summary"><span aria-hidden="true">01 /</span><p>Kaygı, zorlayıcı düşünceler ve erteleme döngüleri içinde; sizin için önemli olan hayata birlikte yönelmek.</p></div><div class="hero-actions"><a class="btn" href="iletisim.html">Bir görüşme planlayın <span aria-hidden="true">↗</span></a><a class="quiet-link" href="#yaklasim">Çalışma biçimim <span aria-hidden="true">↓</span></a></div></div>
  <figure class="hero-figure"><img src="assets/metehan-cakal.jpg" alt="Metehan Çakal, çalışma ortamında görüşme notları üzerinde çalışırken" fetchpriority="high" width="1536" height="2048"><figcaption><span><small>İNSANA DAİR. SİZE ÖZGÜ.</small><strong>Metehan Çakal</strong></span><a href="hakkimda.html" class="portrait-link" aria-label="Metehan Çakal’ı tanıyın">↗</a></figcaption></figure>
  <svg class="hero-thread" viewBox="0 0 600 240" fill="none" aria-hidden="true"><path d="M-20 190c143-7 136-144 271-144 150 0 183 174 71 174S244 19 417 19c97 0 102 70 198 70"/><path d="M-20 201c146-7 143-143 271-143 137 0 169 151 71 151S259 33 417 33c97 0 102 67 198 67"/></svg></div>
  <div class="hero-bottom"><span>Psikolojik danışmanlık. Kendi hızınızda.</span><a href="#alanlar">KEŞFETMEYE DEVAM EDİN <span aria-hidden="true">↓</span></a></div>
</div></section>
<div class="wrap service-strip" aria-label="Görüşme bilgileri">
  <div><span class="strip-icon" aria-hidden="true">◷</span><strong>45 dakika</strong><span>Bireysel görüşme</span></div>
  <div><span class="strip-icon" aria-hidden="true">◎</span><strong>Online</strong><span>Bulunduğunuz yerden</span></div>
  <div><span class="strip-icon" aria-hidden="true">↗</span><strong>ACT yaklaşımı</strong><span>Psikolojik esneklik odağı</span></div>
</div>
<section class="section wrap areas-section" id="alanlar">
  <div class="section-heading"><div><div class="eyebrow"><span class="section-index">01 /</span> ÇALIŞMA ALANLARI</div><h2>Nereden<br>başlayabiliriz?</h2></div><div><p>Sizi buraya getiren ne olursa olsun, ilk adım yaşadığınız güçlüğe birlikte bakmak.</p><a class="text-link" href="calisma-alanlari.html">Tüm çalışma alanları <span aria-hidden="true">↗</span></a></div></div>
  <div class="areas-grid">{area_cards}</div>
</section>
<section class="section dark" id="yaklasim">
  <div class="wrap approach">
    <div class="approach-copy"><div class="eyebrow"><span class="section-index">02 /</span> YAKLAŞIMIM</div><h2>Mesele her zaman<br>iyi hissetmek değil.<br><em>Hayata daha<br>esnek katılmak.</em></h2><p>Kabul ve Kararlılık Terapisi (ACT), zorlayıcı duygu ve düşüncelerle ilişkinize odaklanır. Amaç, onlar varken de sizin için önemli olan yönde adım atabilmektir.</p><a class="text-link" href="yaklasim.html">Yaklaşımı yakından tanıyın <span aria-hidden="true">↗</span></a><div class="approach-footnote"><span aria-hidden="true">✳</span><p>Birbirini destekleyen altı süreç.<br>Merkezinde, sizin yaşamınız.</p></div></div>
    <div class="act-explorer">
      <div class="orbit" role="tablist" aria-label="ACT’nin altı sürecini keşfedin" aria-orientation="horizontal"><svg class="orbit-fallback" viewBox="0 0 520 440" fill="none" aria-hidden="true"><circle cx="260" cy="220" r="151"/><ellipse cx="260" cy="220" rx="151" ry="61"/><ellipse cx="260" cy="220" rx="61" ry="151"/><ellipse cx="260" cy="220" rx="116" ry="151"/></svg><canvas class="orbit-globe" aria-hidden="true"></canvas><div class="orbit-center" aria-hidden="true"><span>PSİKOLOJİK</span><strong>esneklik</strong><span class="orbit-center-star">✳</span></div>{nodes}</div>
      <div id="act-panel" class="act-detail" role="tabpanel" aria-labelledby="act-tab-0" tabindex="0"><span class="act-detail-num">01 / 06</span><div><h3>Şimdiki anla temas</h3><p>Dikkati, şu anda olan bitene yeniden yöneltmek.</p></div><span class="act-detail-arrow" aria-hidden="true">↗</span></div>
      <div class="orbit-controls"><p class="orbit-hint">Bir sürece dokunun, yaklaşımı keşfedin.</p><button class="globe-motion" aria-pressed="false" aria-label="Küre hareketini duraklat"><span class="motion-icon" aria-hidden="true"></span><span>Hareketi duraklat</span></button></div>
    </div>
  </div>
</section>
<section class="section wrap process-section" id="surec">
  <div class="section-heading"><div><div class="eyebrow"><span class="section-index">03 /</span> GÖRÜŞME SÜRECİ</div><h2>Büyük bir karar değil.<br><em>Küçük bir başlangıç.</em></h2></div><p>Nasıl ilerleyeceğimizi, beklentilerinizi ve sürecin size katkısını birlikte değerlendiririz.</p></div>
  <div class="process-grid"><article class="step"><div class="step-top"><span class="step-number">01</span><span>ANLAMAK</span></div><h3>Önce, sizi dinlemek.</h3><p>Yaşadığınız güçlüğü ve hayatınızdaki yerini konuşur; beklentilerinizi, çalışma çerçevesini ve desteğin uygunluğunu birlikte değerlendiririz.</p></article><article class="step"><div class="step-top"><span class="step-number">02</span><span>DENEYİMLEMEK</span></div><h3>Hayatın içinde denemek.</h3><p>Görüşmelerde ele aldığımız becerileri, birlikte belirlediğimiz küçük ve uygulanabilir adımlarla gündelik yaşamınıza taşımayı deneriz.</p></article><article class="step"><div class="step-top"><span class="step-number">03</span><span>DEĞERLENDİRMEK</span></div><h3>Birlikte gözden geçirmek.</h3><p>Adımların hayatınızdaki karşılığına bakar; ihtiyaçlarınıza göre planı uyarlar, sürecin devamını veya tamamlanmasını konuşuruz.</p></article></div>
  <div class="process-note"><span class="status-dot" aria-hidden="true"></span> İlk görüşmede her şeyi anlatmanız beklenmez.<a href="sss.html#soru-10">İlk görüşme hakkında <span aria-hidden="true">↗</span></a></div>
</section>
<section class="section about-band" id="hakkimda"><div class="wrap about-grid"><div class="about-photo"><span class="photo-caption">BİRLİKTE ÇALIŞACAĞINIZ KİŞİ</span><img src="assets/metehan-portre.jpg" alt="Metehan Çakal’ın portresi" loading="lazy" width="1086" height="1448"><span class="about-signature" aria-hidden="true">Metehan.</span></div><div class="about-copy"><div class="eyebrow"><span class="section-index">04 /</span> TANIŞALIM</div><h2>Merhaba,<br><em>ben Metehan.</em></h2><p>Bir insanı, yaşadığı güçlükten ibaret görmüyorum. Benim için danışmanlık; sizi kendi koşullarınız içinde anlamak ve önem verdiğiniz yaşama birlikte alan açmak demek.</p><p class="about-secondary">Uzman Psikolojik Danışman olarak, online bireysel görüşmelerde Kabul ve Kararlılık Terapisi yaklaşımıyla çalışıyorum.</p><div class="credentials"><div><small>LİSANS</small><strong>Kocaeli Üniversitesi</strong><span>Psikolojik Danışmanlık ve Rehberlik</span></div><div><small>YÜKSEK LİSANS</small><strong>Necmettin Erbakan Üniversitesi</strong><span>Rehberlik ve Psikolojik Danışmanlık · Tezsiz</span></div></div><a class="text-link" href="hakkimda.html">Hikâyem ve mesleki yaklaşımım <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section wrap" id="sss"><div class="faq-layout"><div class="faq-aside"><div class="eyebrow"><span class="section-index">05 /</span> MERAK EDİLENLER</div><h2>Biraz daha açıklık.<br><em>Biraz daha rahatlık.</em></h2><p>Başlamadan önce aklınızda sorular olması çok doğal. Bazı yanıtları burada bulabilirsiniz.</p><a class="text-link" href="sss.html">18 sorunun tamamını görün <span aria-hidden="true">↗</span></a></div>{faq_html}</div></section>
{contact}
'''
